authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
     path('register/', views.register_view, name='register'),
     path('register/create', views.register_create, name='register_create'),
     path('login/', views.login_view, name='login'),
     path('login/acess/', views.login_create, name='login_create'),
     path('logout/', views.logout_view, name='logout'),

     path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

     path('dashboard/recipe/<int:id>/edit/',
          views.DashboardRecipeEdit.as_view(),
          name='dashboard_recipe_edit'),

     path('dashboard/recipe/create/', views.DashboardRecipeEdit.as_view(),
          name='dashboard_recipe_create'),

     path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(),
          name='dashboard_recipe_delete'),

     path('dashboard/recipe/<int:id>/',
          views.DashboardRecipeUnpublishView.as_view(),
          name='recipe_not_published'),

     path('dashboard/recipe/unpublish',
          views.DashboardRecipeUnpublish.as_view(),
          name='dashboard_recipe_unpublish'),

     path('profile/<int:id>/', views.ProfileView.as_view(),
          name='profile'),

     path('myprofile/', views.MyProfileView.as_view(),
          name="myprofile"),

     path('myprofile/bio_edit/', views.BioEditView.as_view(),
          name="myprofile_bio_edit"),

     path('myprofile/edit/', views.MyProfileEditView.as_view(),
          name="myprofile_edit"),

     path('myprofile/edit/password/',
          views.PasswordsChangeView.as_view(),
          name='myprofile_edit_password'),

     path('myprofile/edit/password/done/',
          views.PasswordsDoneChangeView.as_view(),
          name='myprofile_edit_password_done'),
]

recipes/urls.py
from django.urls import path
from .views import views_site, views_api

app_name = 'recipes'

urlpatterns = [
     # Recipe
     path('', views_site.RecipeListViewHome.as_view(), name='home'),
     path('recipes/<int:pk>/', views_site.RecipeDetail.as_view(),
          name='recipe'),
     path('category/<int:category_id>/',
          views_site.RecipeListViewCategory.as_view(), name='category'),
     path('recipes/search/', views_site.RecipeListViewSearch.as_view(),
          name='search'),
     path('recipes/api/v1/', views_site.RecipeListViewHomeApi.as_view(),
          name='recipes_api_v1',
          ),
     path('recipes/api/v1/<int:pk>/', views_site.RecipeDetailAPI.as_view(),
          name='recipes_detail_api_v1',
          ),
     path('recipes/tags/<slug:slug>/', views_site.RecipeListViewTag.as_view(),
          name='tag'),

     # Toggle menu
     path('menu/', views_site.menu, name='menu'),

     # API View
     path('recipes/api/v2/', views_api.recipe_api_list,
          name='recipes_api_v2'),
     path('recipes/api/v2/<int:pk>/', views_api.recipe_api_detail,
          name='recipes_api_v2_detail'),
     path('recipes/api/v2/tag/<int:pk>/', views_api.recipe_api_tag,
          name='recipes_api_v2_tag'),
]

recipes_site/recipes_site/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

recipes_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/partials/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ html_language }}">
<head>

    {% include "partials/links.html" %}
    <title>{% block title %}{% endblock title %}{% translate "Recipes" %}</title>

</head>

<body>
    {% include "partials/menu.html" %}
    {% include "partials/header.html" %}
    {% include "partials/search.html" %}
    <main>
        {% block content %}{% endblock content %}
        {% include "partials/pagination.html" %}
    </main>
    
    {% include "partials/footer.html" %}
    <script src="{% static "js/scripts.js" %}"></script>

</body>

</html>

templates/partials/footer.html
{% load i18n %}
<footer class="footer-container">
    <div class="developer">
        <a href="https://github.com/Rafael-soares-oliveira">{% translate "By" %} Rafael Oliveira</a>
    </div>
    <div class="powered">
        <span>{% translate "Powered by" %} Django</span>
    </div>
</footer>

templates/partials/forms.html
{% load i18n %}
<div class="main-content">
    <form action="{{ form_action }}" method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-content form-content-grid">
            {% for field in form %}
                <div class="form-group  {{ field.field.widget.attrs.class }}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}

                    {% if field.help_text %}
                        <p class="help-text">
                            {{field.help_text }}
                        </p>
                    {% endif %}
                    
                    {{ field.errors }}
                </div>

                {% if field.name == 'cover' and field.value.url %}
                <div class="span-2 img-cover-edit">
                    <img src="{{ field.value.url }}" alt="Capa para {{ recipe.title }}">
                </div>
                {% endif %}
            {% endfor %}
        </div>
        
        <div class="form-content form-content-grid">
            <div class="form-group" aria-label='Button to confirm'>
                <button type="submit">{% translate "Send" %}</button>
            </div>
        </div>
    </form>
</div>

templates/partials/header.html
{% load i18n %}
<header class="header">
    <div>
        <a class='header-logo' href="{% url "recipes:home" %}">
            <i class="fas fa-utensils"></i>
            <span>{% translate "Recipes" %}</span>
        </a>
    </div>
</header>

templates/partials/home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static "css/style_base.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="header-container">
        <div class="header container">
            <a href="{% url "recipes:home" %}">
                <i class='fas fa-utensils'></i>
                <span>Recipes</span>
            </a>
        </div>
    </div>
</body>
</html>

templates/partials/links.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/scripts.js' %}">

templates/partials/menu.html
{% load i18n %}
<button class="button-show-menu button-show-menu-visible">
    <i class="fas fa-bars"></i>
    <span class="hidden-text">{% translate "Show menu" %}</span>
</button>
    
<div class="menu-container menu-hidden">
    <button class="button-close-menu button-close-menu-visible">
      <i class="fas fa-times-circle"></i>
      <span class="hidden-text">{% translate "Close menu" %}</span>
    </button>

    <div class="menu-content">
      <nav class="menu-nav">
        {% if not request.user.is_authenticated %}
            <a href="{% url 'recipes:home' %}">{% translate "Home" %}</a>
            <form action="{% url 'authors:register' %}" method='POST'>
                {% csrf_token %}
                <button type="submit">{% translate "Register" %}</button>
            </form>
            <form action="{% url 'authors:login' %}" method='POST'>
                {% csrf_token %}
                <button id='login-button' type="submit">{% translate "Login" %}</button>
            </form>
        {% else %}
            <span>{{ request.user.first_name }} ({{ request.user.username }})</span>
            <a href="{% url 'recipes:home' %}">{% translate "Home" %}</a>
            <a href="{% url 'authors:myprofile' %}">{% translate "My Profile" %}</a>
            <form action="{% url "authors:dashboard" %}" method='POST'>
                {% csrf_token %}
                <button type="submit">{% translate "Dashboard" %}</button>
            </form>
            <form action="{% url 'authors:logout' %}" method='POST'>
                {% csrf_token %}
                <button type="submit">{% translate "Logout" %}</button>
            </form>
        {% endif %}
      </nav>
    </div>
</div>

templates/partials/messages.html
{% if messages %}
    <div class="main-content main-content-list container messages-container">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/partials/pagination.html
{% if recipes.has_other_pages %}

    <div class="pagination" aria-label="Pagination">

        {% if pagination_range.first_page_out_of_range %}
        <div class="page-link" aria-label="Go to page 1">
            <a  href="?page=1{{ additional_url_query }}">1</a>
        </div>
        <div class="page-item">
            <span>...</span>
        </div>
        {% endif %}

        {% for page in pagination_range.pagination %}
            {% if pagination_range.current_page == page %}
            <div class="page-link page-current" aria-label="Current page {{ page }}">
                <a href="?page={{ page }}{{ additional_url_query }}">
                    {{ page }}
                </a>
            </div>
            {% else %}
            <div class="page-link" aria-label="Go to page {{ page }}">
                <a href="?page={{ page }}{{ additional_url_query }}">
                    {{ page }}
                </a>
            </div>
            {% endif %}
        {% endfor %}

        {% if pagination_range.last_page_out_of_range %}
            <div class="page-item">
                <span>...</span>
            </div>
            <div class="page-link" aria-label="Go to last page {{ last_page }}">
                <a href="?page={{ last_page }}{{ additional_url_query }}">
                    {{ last_page }}
                </a>
            </div>
        {% endif %}

    </div>
{% endif %}

templates/partials/recipe_not_published.html
{% load i18n %}
<div class="recipe-edit-button">
    <form action="{% url "authors:dashboard_recipe_edit" recipe.id %}">
        <button>{% translate "Edit Recipe" %}</button>
    </form>
    <form action="{% url "authors:dashboard" %}">
        <button>{% translate "Dashboard" %}</button>
    </form>
</div>

<div class="main-content main-content-detail container">
    <div class="recipe recipe-list-item">
        <div class="recipe-cover">
            <img src="{{ recipe.cover.url }}" alt="">
        </div>
        <div class="recipe-content">
            <div class="recipe-title">
                <h2>{{ recipe.title }}</h2>
            </div>
            <div class="recipe-author">
                <span>
                    <i class="fas fa-user"></i>
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                </span>
                <span>
                    <i class="fas fa-calendar-alt"></i>
                    {{ recipe.created_at |date:"d/m/Y" }}
                </span>
            </div>
            <div class="recipe-description">
                <span>
                    {{ recipe.description }}
                </span>
            </div>
            <div class="recipe-preparation-info-container">
                <div class="recipe-preparation-info">
                    <h3><i class="fas fa-clock"></i> {% translate "Preparation" %}</h3>
                    <span>{{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}</span>
                </div>
                <div class="recipe-preparation-info">
                    <h3><i class="fas fa-pizza-slice"></i> {% translate "Servings" %}</h3>
                    <span>{{ recipe.servings }} {{ recipe.servings_unit }}</span>
                </div>
            </div>

            <div class="recipe-preparation-title">
                <h2><i class="fas fa-blender"></i> {% translate "Directions" %}</h2>
            </div>
            <div class="recipe-preparation">
                {% if recipe.preparation_step_is_html is True %}
                    {{ recipe.preparation_step|safe }}
                {% else %}
                    {{ recipe.preparation_step|linebreaksbr }}
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/partials/recipes_base.html
{% load i18n %}

<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url "recipes:recipe" recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="">
        </a>
    </div>
    <div class="recipe-content">
        <div class="recipe-title">
            <a href="{% url "recipes:recipe" recipe.id %}">
                <h2>{{ recipe.title }}</h2>
            </a>
        </div>
        <div class="recipe-author">
            <span class="author-name">
                <i class="fas fa-user"></i>
                <a href="{% url "authors:profile" recipe.author.profile.id %}">{{ recipe.author.first_name }} {{ recipe.author.last_name }}</a>
            </span>
            <span>
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at |date:"d/m/Y" }}
            </span>
            <a href="{% url "recipes:category" recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                {{ recipe.category.name }}
            </a>
        </div>
        <div class="recipe-description">
            <span>
                {{ recipe.description }}
            </span>
        </div>
        <div class="recipe-preparation-info-container">
            <div class="recipe-preparation-info">
                <h3><i class="fas fa-clock"></i> {% translate "Preparation" %}</h3>
                <span>{{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}</span>
            </div>
            <div class="recipe-preparation-info">
                <h3><i class="fas fa-pizza-slice"></i> {% translate "Servings" %}</h3>
                <span>{{ recipe.servings }} {{ recipe.servings_unit }}</span>
            </div>
        </div>


        {% if is_detail_page is not True %}
            <footer class="recipe-footer">
                <a href="{% url "recipes:recipe" recipe.id %}" class="recipe-read-more button-full-width">
                    <i class="fas fa-eye"></i>
                    <span>{% translate "Read More..." %}</span>
                </a>
            </footer>
        {% endif %}

        {% if is_detail_page is True %}
            <div class="recipe-preparation-title">
                <h2><i class="fas fa-blender"></i> {% translate "Directions" %}</h2>
            </div>
            <div class="recipe-preparation">
                {% if recipe.preparation_step_is_html is True %}
                    {{ recipe.preparation_step|safe }}
                {% else %}
                    {{ recipe.preparation_step|linebreaksbr }}
                {% endif %}
            </div>
        {% endif %}

        {% if recipe.tags.all %}
            <p class="tags">
                Tags:
                {% for tag in recipe.tags.all %}
                    <a href="{% url 'recipes:tag' tag.slug %}" class='tag-link'>
                        {{ tag.name }}
                    </a>,
                {% endfor %}
            </p>
        {% endif %}
    </div>
</div>

templates/partials/search.html
{% load i18n %}
<div class="search-container container">
    <form action="{% url "recipes:search" %}" method="get" class="search-form" autocomplete="off">
        <input type="search" name="q" class="search-input" placeholder='{% translate "Search recipe" %}' required>
        <button type="submit" class="search-button">
            <i class="fa fa-search"></i>
        </button>
    </form>
</div>