authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
     path('register/', views.register_view, name='register'),
     path('register/create', views.register_create, name='register_create'),
     path('login/', views.login_view, name='login'),
     path('login/acess/', views.login_create, name='login_create'),
     path('logout/', views.logout_view, name='logout'),

     path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

     path('dashboard/recipe/<int:id>/edit/',
          views.DashboardRecipeEdit.as_view(),
          name='dashboard_recipe_edit'),

     path('dashboard/recipe/create/', views.DashboardRecipeEdit.as_view(),
          name='dashboard_recipe_create'),

     path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(),
          name='dashboard_recipe_delete'),

     path('dashboard/recipe/<int:id>/',
          views.DashboardRecipeUnpublishView.as_view(),
          name='recipe_not_published'),

     path('dashboard/recipe/unpublish',
          views.DashboardRecipeUnpublish.as_view(),
          name='dashboard_recipe_unpublish'),

     path('profile/<int:id>/', views.ProfileView.as_view(),
          name='profile'),

     path('myprofile/', views.MyProfileView.as_view(),
          name="myprofile"),

     path('myprofile/bio_edit/', views.BioEditView.as_view(),
          name="myprofile_bio_edit"),

     path('myprofile/edit/', views.MyProfileEditView.as_view(),
          name="myprofile_edit"),

     path('myprofile/edit/password/',
          views.PasswordsChangeView.as_view(),
          name='myprofile_edit_password'),

     path('myprofile/edit/password/done/',
          views.PasswordsDoneChangeView.as_view(),
          name='myprofile_edit_password_done'),
]

recipes/urls.py
from django.urls import path
from .views import views_site, views_api

app_name = 'recipes'

urlpatterns = [
     # Recipe
     path('', views_site.RecipeListViewHome.as_view(), name='home'),
     path('recipes/<int:pk>/', views_site.RecipeDetail.as_view(),
          name='recipe'),
     path('category/<int:category_id>/',
          views_site.RecipeListViewCategory.as_view(), name='category'),
     path('recipes/search/', views_site.RecipeListViewSearch.as_view(),
          name='search'),
     path('recipes/api/v1/', views_site.RecipeListViewHomeApi.as_view(),
          name='recipes_api_v1',
          ),
     path('recipes/api/v1/<int:pk>/', views_site.RecipeDetailAPI.as_view(),
          name='recipes_detail_api_v1',
          ),
     path('recipes/tags/<slug:slug>/', views_site.RecipeListViewTag.as_view(),
          name='tag'),

     # Toggle menu
     path('menu/', views_site.menu, name='menu'),

     # API View
     path('recipes/api/v2/', views_api.recipe_api_list,
          name='recipes_api_v2'),
     path('recipes/api/v2/<int:pk>/', views_api.recipe_api_detail,
          name='recipes_api_v2_detail'),
     path('recipes/api/v2/tag/<int:pk>/', views_api.recipe_api_tag,
          name='recipes_api_v2_tag'),
]

recipes_site/recipes_site/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

recipes_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from collections import defaultdict
import os
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
from django.utils.text import slugify
from tag.models import Tag
from django.utils.translation import gettext as _
from PIL import Image


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Recipe(models.Model):
    title = models.CharField(max_length=65, verbose_name=_('Title'))
    description = models.CharField(
        max_length=165, verbose_name=_('Description'))
    slug = models.SlugField(unique=True, null=True)
    preparation_time = models.IntegerField(verbose_name=_('Preparation Time'))
    preparation_time_unit = models.CharField(
        max_length=65, verbose_name=_('Preparation Time Unit'))
    servings = models.IntegerField(verbose_name=_('Servings'))
    servings_unit = models.CharField(
        max_length=65, verbose_name=_('Servings Unit'))
    preparation_step = models.TextField(verbose_name=_('Preparation Step'))
    preparation_step_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='media/covers/%Y/%m/%d', blank=True,
        default='',
        verbose_name=_('Cover'))
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True, default='')

    def __str__(self) -> str:
        return self.title

    @staticmethod
    def resize_image(image, new_width=800):
        image_full_path = os.path.join(settings.MEDIA_ROOT, image.name)
        image_pillow = Image.open(image_full_path)
        original_width, original_height = image_pillow.size

        if original_width <= new_width:
            image_pillow.close()
            return

        new_height = round(new_width * original_height / original_width)
        new_image = image_pillow.resize((new_width, new_height), Image.LANCZOS)
        new_image.save(
            image_full_path,
            optimize=True,
            quality=50,
            )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.title)}'
            self.slug = slug

        saved = super().save(*args, **kwargs)

        if self.cover:
            try:
                self.resize_image(self.cover, 800)
            except FileNotFoundError:
                ...

        return saved

    def clean(self, *args, **kwargs):
        error_messages = defaultdict(list)
        recipe_from_db = Recipe.objects.filter(title__iexact=self.title
                                               ).first()
        if recipe_from_db:
            if recipe_from_db.pk != self.pk:
                error_messages['title'].append(
                    _('Found recipes with the same title')
                )

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = _('Recipe')
        verbose_name_plural = _('Recipes')

authors/views/profile.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView
from authors.forms import BioFormEdit, MyProfileForm, ProfileFormEdit
from authors.models import Profile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView)


class ProfileView(TemplateView):
    template_name = 'pages/profile.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        profile_id = context.get('id')
        profile = get_object_or_404(Profile.objects.filter(
            pk=profile_id,
        ).select_related('author'), pk=profile_id)
        return self.render_to_response(
            {
                **context,
                'profile': profile,
            }
        )


@method_decorator(
    login_required(login_url='authors:login', redirect_field_name='next'),
    name='dispatch'
    )
class MyProfileView(UpdateView):
    template_name = 'pages/my_profile.html'
    form_class = MyProfileForm
    success_url = reverse_lazy('authors:myprofile_edit')

    def get_object(self):
        return self.request.user


@method_decorator(
    login_required(login_url='authors:login', redirect_field_name='next'),
    name='dispatch'
    )
class BioEditView(UpdateView):
    template_name = 'pages/bio_edit.html'
    form_class = BioFormEdit
    success_url = reverse_lazy('authors:myprofile')

    def get_object(self):
        return self.request.user.profile

    def form_valid(self, form):
        messages.success(self.request, 'Your bio was update sucessfully.')
        return super(BioEditView, self).form_valid(form)


@method_decorator(
    login_required(login_url='authors:login', redirect_field_name='next'),
    name='dispatch'
    )
class MyProfileEditView(UpdateView):
    template_name = 'pages/profile_edit.html'
    form_class = ProfileFormEdit
    success_url = reverse_lazy('authors:myprofile')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Your profile was update sucessfully.')
        return super().form_valid(form)


@method_decorator(
    login_required(login_url='authors:login', redirect_field_name='next'),
    name='dispatch'
    )
class PasswordsChangeView(PasswordChangeView):
    success_url = reverse_lazy('authors:myprofile_edit_password')
    template_name = 'pages/change-password.html'
    success_url = reverse_lazy('authors:myprofile_edit_password_done')

    def form_valid(self, form):
        messages.success(self.request, 'Your password was update sucessfully.')
        return super().form_valid(form)


@method_decorator(
    login_required(login_url='authors:login', redirect_field_name='next'),
    name='dispatch'
    )
class PasswordsDoneChangeView(PasswordChangeDoneView):
    template_name = 'pages/password-done.html'

recipes/views.py
from django.http import Http404
from django.shortcuts import render
from recipes.models import Recipe
from django.db.models import Q
from utils.make_pagination import make_pagination
import os
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.forms.models import model_to_dict
from tag.models import Tag
from django.utils import translation
from django.utils.translation import gettext as _

PER_PAGE = os.environ.get('PER_PAGE', 10)


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    ordering = ['-id']

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.select_related('author', 'category')
        qs = qs.prefetch_related('tags', 'author__profile')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('recipes'),
            PER_PAGE
        )
        html_language = translation.get_language()

        ctx.update(
            {
                'recipes': page_obj, 'pagination_range': pagination_range,
                'last_page': pagination_range['total_pages'],
                'html_language': html_language,
                })
        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = "pages/home.html"


class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = "pages/home.html"

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data()['recipes']
        recipes_list = recipes.object_list.values()
        return JsonResponse(
            list(recipes_list),
            safe=False
        )


class RecipeListViewCategory(RecipeListViewBase):
    template_name = "pages/category-view.html"

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')
        ctx.update({
            'title': f'{ctx.get("recipes")[0].category.name} - '
            f'{category_translation} | '})
        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
            category__id=self.kwargs.get('category_id')
        )

        if not qs:
            raise Http404()

        return qs


class RecipeListViewSearch(RecipeListViewBase):
    template_name = "pages/search-view.html"

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '').strip()

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term),
                ),
            is_published=True,
            )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('recipes'),
            PER_PAGE
        )
        ctx.update(
            {'recipes': page_obj,
             'pagination_range': pagination_range,
             'last_page': pagination_range['total_pages'],
             'additional_url_query': f'?q={search_term}',
             'title': f'Search for "{search_term}" | ',
             'search_term': search_term,
             }
        )
        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    template_name = "pages/recipe-view.html"
    context_object_name = 'recipe'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )

        if not qs:
            raise Http404()

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_page': True,
        })
        return ctx


class RecipeDetailAPI(RecipeDetail):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        recipe_dict['created_at'] = str(recipe.created_at)
        recipe_dict['updated_at'] = str(recipe.created_at)

        if recipe_dict.get('cover'):
            recipe_dict['cover'] = recipe_dict['cover'].url
        else:
            recipe_dict['cover'] = ''

        del recipe_dict['is_published']
        del recipe_dict['preparation_step_is_html']

        return JsonResponse(recipe_dict, safe=False)


class RecipeListViewTag(RecipeListViewBase):
    template_name = 'pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')
        ).first()

        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'

        ctx.update({
            'page_title': page_title,
        })

        return ctx


def menu(request):
    return render(request, 'partials/menu.html')

recipes/views/views_api.py
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from ..models import Recipe
from ..serializers import RecipeSerializer, TagSerializer
from tag.models import Tag


@api_view(http_method_names=['get', 'post'])
def recipe_api_list(request):
    if request.method == 'GET':
        recipes = Recipe.objects.filter(
            is_published=True
            ).order_by('-id').select_related(
                'category', 'author').prefetch_related(
                    'tags'
                )
        serializer = RecipeSerializer(instance=recipes, many=True, context={
            'request': request
        })
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = RecipeSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        # serializer.save()
        return Response(
            serializer.validated_data,
            status=status.HTTP_201_CREATED
        )


@api_view()
def recipe_api_detail(request, pk):
    recipes = get_object_or_404(
        Recipe.objects.filter(
            is_published=True
            ).order_by('-id'), pk=pk)
    serializer = RecipeSerializer(
        instance=recipes,
        many=False,
        context={
            'request': request
            })
    return Response(serializer.data)


@api_view()
def recipe_api_tag(request, pk):
    tag = get_object_or_404(
        Tag.objects.all(), pk=pk)
    serializer = TagSerializer(
        instance=tag,
        many=False,
        context={
            'request': request
            })
    return Response(serializer.data)

tag/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/category-view.html
{% extends "partials/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'partials/recipes_base.html' %}
    {% endfor %}
</div>
{% endblock content %}

templates/pages/change-password.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Change Password" %} {{ request.user.first_name }} | {% endblock title %}

{% block content %}
        <div class="center">
            <h2>{% translate "Change Password" %}</h2>
        </div>

        <div class="form-content form-content-grid">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-content form-content-grid">
                    <div class="form-group" aria-label='Button to confirm the registration'>
                        <button type="submit">{% translate "Change Password" %}</button>
                    </div>
                </div>
            </form>
        </div>
{% endblock content %}

templates/pages/dashboard.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Dashboard" %} | {% endblock title %}

{% block content %}
    {% include "partials/messages.html" %}
    <div class="main-content center container">
        <h2>{% translate "Dashboard" %} {{ request.user.first_name }} {{ request.user.last_name }}</h2>
        <form action="{% url "authors:dashboard_recipe_create"%}" class="button-create-recipe">
            <button type="submit">
                <i class="fas fa-plus"></i> {% translate "Create recipe" %}
            </button>
        </form>
        <div class="authors-dashboard-container">
            <div class="published-container">
                <h3>{% translate "Recipes Published" %} - {{ number_recipes_published }}</h3> 
                <ul>
                    {% for recipe in recipes_published %}
                        <li class="recipe-dashboard-list">
                            <a href="{% url "recipes:recipe" recipe.id %}">{{ recipe.title }}</a>
                            <form class="form-unpublish" action="{% url 'authors:dashboard_recipe_unpublish' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{ recipe.id }}">
                                <button type="submit"><i class="fas fa-times"></i> {% translate "Unpublish" %}</button>
                            </form>
                        </li>
                    {% empty %}
                    <li>
                        <p>{% translate "You do not have a recipe." %}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div>
                <h3>{% translate "Recipes not yet Published" %} - {{ number_recipes_not_published }}</h3>
                <ul class="not-published-container">
                    {% for recipe in recipes_not_published %}
                        <li class="recipe-dashboard-list">
                            <a href="{% url "authors:recipe_not_published" recipe.id %}">{{ recipe.title }}</a>
                            <form class="form-delete" action="{% url 'authors:dashboard_recipe_delete' %}"  method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{ recipe.id }}">
                                <button type="submit"><i class="fas fa-trash"></i> {% translate "Delete" %}</button>
                            </form>
                        </li>
                    {% empty %}
                    <li>
                        <p>{% translate "You do not have a recipe." %}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock content %}

templates/pages/dashboard_recipe_edit.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Recipe Edit" %} | {% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>{% translate "Recipe Edit" %}</h2>
        <div class="authors-dashboard-container">
            {% include "partials/forms.html" %}
        </div>
    </div>

{% endblock content %}

templates/pages/home.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Home" %} | {% endblock title %}


{% block content %}
    
    <div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include "partials/recipes_base.html" %}
    {% empty %}
        <div class="center m-y">
            <h1>{% translate "No recipes found here." %}</h1>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

templates/pages/login.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Login" %} | {% endblock title %}

{% block content %}

    {% include "partials/messages.html" %}

    <div class="form-content">
        <h2>{% translate "Login" %}</h2>

        {% if request.user.is_authenticated %}
        <div class="logged">
            {% translate "Your are logged in with" %} {{ request.user.username }}. 
            <a href="{% url 'authors:dashboard' %}">{% translate "See your recipes" %}</a> or
            <a href="{% url 'authors:myprofile' %}">{% translate "See your profile" %}</a>.
        </div>
        <form class="logged-logout" action="{% url 'authors:logout' %}" method='POST'>
            {% csrf_token %}
            <button type="submit">{% translate "Logout" %}</button>
        </form>
        {% endif %}
    </div>

    {% if not request.user.is_authenticated %}
        {% include "partials/forms.html" %}
    {% endif %}

{% endblock content %}

templates/pages/my_profile.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "My Profile" %} | {% endblock title %}

{% block content %}
        <div class="main-content main-content-detail container center">
            <h2>{% translate "Profile" %} {{ request.user.first_name }} {{ request.user.last_name }}</h2>
            <p class='bio'>" {{ request.user.profile.bio }} "</p>
            <div class="form-content form-content-grid">
                <a href="{% url "authors:myprofile_bio_edit" %}">
                    <button>{% translate "Edit Bio" %}</button>
                </a>
            </div>
        </div>
        {% include "partials/messages.html" %}
        <div class="form-content-read form-content-grid">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-content form-content-grid">
                    <div class="form-group" aria-label='Button to edit the profile'>
                        <a href="{% url "authors:myprofile_edit" %}"><button>{% translate "Edit" %}</button></a>
                    </div>
                </div>
            </form>
        </div>
{% endblock content %}

templates/pages/profile.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Profile" %} {{ profile.authors.id }} | {% endblock title %}

{% block content %}
        <div class="main-content main-content-detail container center">
            <h2>{% translate "Profile" %} {{ profile.author.first_name }} {{ profile.author.last_name }}</h2>
            <p>{{ profile.bio }}</p>
        </div>
{% endblock content %}

templates/pages/profile_edit.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Profile" %} {{ request.user.first_name }} | {% endblock title %}

{% block content %}
        <div class="main-content main-content-detail container center">
            <h2>{% translate "Profile Edit" %}</h2>
        </div>
        <div class="form-content form-content-grid">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-content form-content-grid">
                    <div class="form-group" aria-label='Button to confirm the registration'>
                        <button type="submit">{% translate "Send" %}</button>
                    </div>
                </div>
            </form>
        </div>
{% endblock content %}

templates/pages/recipe-view.html
{% extends "partials/base.html" %}

{% block title %}{{ recipe.title }} | {% endblock title %}

{% block content %}
    {% if recipe.is_published %}
        <div class="main-content main-content-detail container">
            {% include "partials/recipes_base.html" %}
        </div>

    {% else %}
        {% include "partials/messages.html" %}
        <div class="main-content main-content-detail container">
            {% include "partials/recipe_not_published.html" %}
        </div>
    {% endif %}
{% endblock content %}

templates/pages/register_created.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Register Sucess" %} | {% endblock title %}

{% block content %}

    <div class="form-content">
        <div class="message message-sucess">
            {% translate "Your user is created, please" %} <a href="{% url "authors:login" %}">{% translate "login" %}</a>.
        </div>
    </div>

{% endblock content %}

templates/pages/register_view.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{% translate "Register" %} | {% endblock title %}

{% block content %}

    <div class="form-content">
        <h2>{% translate "Register" %}</h2>
    </div>

    {% include "partials/forms.html" %}

{% endblock content %}

templates/pages/search-view.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="center search-text">
    <h1>{% translate "Results find for:" %} {{ search_term }}</h1>
</div>
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'partials/recipes_base.html' %}
    {% empty %}
        <div class="center m-y">
            <h1>{% translate "No recipes found here." %}</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

templates/pages/tag.html
{% extends "partials/base.html" %}
{% load i18n %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include "partials/recipes_base.html" %}
        {% empty %}
            <div class="center m-y">
                <h1>{% translate "No recipes found here!" %}</h1>
            </div>
        {% endfor %}
    </div>
{% endblock content %}